---
- name:
  hosts: alla
  become: true
  vars:
    git_repository: "https://github.com/arekaws1/Ansible_roles.git"
    git_branch: "main"
  tasks:
    - name: Create a dir for roles
      file:
        path: /etc/ansible/roles
        state: directory
        mode: '0755'
    - name: Git checkout
      git:
        force: yes
        update: yes
        repo: "{{git_repository}}"
        dest: "/etc/ansible/roles"
        version: "{{git_branch}}"
